"""FR-11: PDF export of simplified output (reportlab, in-memory bytes)."""
from __future__ import annotations

import io
import re


def _clean(text: str) -> str:
    """Strip markdown emphasis so the PDF shows plain text."""
    return re.sub(r"[*_`>#]", "", text or "")


def build_simplified_pdf(document_type: str, reading_level: str, sections: list[dict]) -> bytes:
    """Render simplified sections to a simple, printable PDF."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=20 * mm, rightMargin=20 * mm,
                            topMargin=20 * mm, bottomMargin=20 * mm, title="LexiClarity Simplified Document")
    styles = getSampleStyleSheet()
    story = [
        Paragraph("LexiClarity — Simplified Legal Document", styles["Title"]),
        Paragraph(f"Document type: {_clean(document_type)} · Reading level: {_clean(reading_level)}", styles["Normal"]),
        Spacer(1, 6 * mm),
    ]
    for s in sections:
        story.append(Paragraph(_clean(s.get("original_heading", "Section")), styles["Heading2"]))
        story.append(Paragraph(_clean(s.get("plain_text", "")).replace("\n", "<br/>"), styles["Normal"]))
        if s.get("source_span"):
            story.append(Paragraph(f"<i>Source: {_clean(s['source_span'])}</i>", styles["Normal"]))
        story.append(Spacer(1, 4 * mm))
    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph(
        "<i>Informational only — not legal advice. Generated by LexiClarity; consult a qualified lawyer before acting.</i>",
        styles["Normal"],
    ))
    doc.build(story)
    return buf.getvalue()


def build_lawyer_prep_pdf(data: dict) -> bytes:
    """Render the lawyer-preparation pack to a printable one-to-two page PDF."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import ListFlowable, ListItem, Paragraph, SimpleDocTemplate, Spacer

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=20 * mm, rightMargin=20 * mm,
                            topMargin=20 * mm, bottomMargin=20 * mm, title="LexiClarity Lawyer Preparation Pack")
    styles = getSampleStyleSheet()

    def bullets(items: list[str]):
        return ListFlowable([ListItem(Paragraph(_clean(i), styles["Normal"])) for i in items], bulletType="bullet")

    story = [
        Paragraph("Lawyer Preparation Pack", styles["Title"]),
        Paragraph(_clean(data.get("case_summary", "")), styles["Normal"]),
        Spacer(1, 4 * mm),
        Paragraph("Parties & responsibilities", styles["Heading2"]),
        bullets([f"{p.get('name', '')} ({p.get('role', '')}): {p.get('responsibilities', '')}" for p in data.get("parties", [])]),
        Paragraph("Important dates & triggers", styles["Heading2"]),
        bullets([f"{d.get('date_or_trigger', '')}: {d.get('what_happens', '')}" for d in data.get("important_dates", [])]),
        Paragraph("Financial obligations", styles["Heading2"]),
        bullets([f"{f.get('item', '')}: {f.get('amount', '')} (due {f.get('due', '')})" for f in data.get("financial_obligations", [])]),
        Paragraph("Top risks", styles["Heading2"]),
        bullets([f"{r.get('risk', '')}: {r.get('why', '')}" for r in data.get("top_risks", [])]),
        Paragraph("Missing or ambiguous information", styles["Heading2"]),
        bullets(data.get("missing_or_ambiguous", [])),
        Paragraph("Questions for your lawyer", styles["Heading2"]),
        bullets(data.get("questions_for_lawyer", [])),
        Paragraph("Documents to bring", styles["Heading2"]),
        bullets(data.get("documents_to_bring", [])),
        Paragraph("Timeline", styles["Heading2"]),
        bullets([f"{t.get('when', '')}: {t.get('event', '')}" for t in data.get("timeline", [])]),
        Spacer(1, 6 * mm),
        Paragraph("<i>Informational only — not legal advice. Generated by LexiClarity; share with a qualified lawyer.</i>", styles["Normal"]),
    ]
    doc.build(story)
    return buf.getvalue()
