"""FR-11: PDF export of simplified output (reportlab, in-memory bytes)."""
from __future__ import annotations

import io
import re


def _clean(text: str) -> str:
    """Strip markdown emphasis so the PDF shows plain text."""
    return re.sub(r"[*_`>#]", "", text or "")


def build_simplified_pdf(document_type: str, reading_level: str, sections: list[dict]) -> bytes:
    """Render simplified sections to a simple, printable PDF."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=20 * mm, rightMargin=20 * mm,
                            topMargin=20 * mm, bottomMargin=20 * mm, title="LexiClarity Simplified Document")
    styles = getSampleStyleSheet()
    story = [
        Paragraph("LexiClarity — Simplified Legal Document", styles["Title"]),
        Paragraph(f"Document type: {_clean(document_type)} · Reading level: {_clean(reading_level)}", styles["Normal"]),
        Spacer(1, 6 * mm),
    ]
    for s in sections:
        story.append(Paragraph(_clean(s.get("original_heading", "Section")), styles["Heading2"]))
        story.append(Paragraph(_clean(s.get("plain_text", "")).replace("\n", "<br/>"), styles["Normal"]))
        if s.get("source_span"):
            story.append(Paragraph(f"<i>Source: {_clean(s['source_span'])}</i>", styles["Normal"]))
        story.append(Spacer(1, 4 * mm))
    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph(
        "<i>Informational only — not legal advice. Generated by LexiClarity; consult a qualified lawyer before acting.</i>",
        styles["Normal"],
    ))
    doc.build(story)
    return buf.getvalue()
